#配置服务器
server:
  #端口号
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      max-wait: 60000
      min-idle: 10
      test-while-idle: true
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid
